apiVersion: v2
type: application
appVersion: "22.05"
description: A chart for deploying and managing a single Galaxy out-of-the-box instance on Managed Kubernetes clusters (GKE)
name: galaxykubeman
version: 2.2.0
icon: https://galaxyproject.org/images/galaxy-logos/galaxy_project_logo_square.png
dependencies:
  - name: nfs-server-provisioner
    repository: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/
    version: 1.5.0
    alias: nfs
  - name: galaxy
    repository: https://raw.githubusercontent.com/cloudve/helm-charts/anvil/
    version: 5.3.1-anvil.1
