apiVersion: v2
type: application
appVersion: "24.2.0"
description: A chart for deploying and managing a single Galaxy out-of-the-box instance on Managed Kubernetes clusters (GKE)
name: galaxykubeman
version: 3.0.0
icon: https://galaxyproject.org/images/galaxy-logos/galaxy_project_logo_square.png
dependencies:
  - name: nfs-server-provisioner
    repository: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/
    version: 1.8.0
    alias: nfs
