dependencies:
  - name: nfs-server-provisioner
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 1.1.1
    alias: nfs
  - name: galaxy-cvmfs-csi
    repository: https://raw.githubusercontent.com/cloudve/helm-charts/anvil/
    version: 1.3.2
    alias: cvmfs
  - name: galaxy
    repository: https://raw.githubusercontent.com/cloudve/helm-charts/anvil/
    version: 3.4.1
