tools:
  __DATA_FETCH__:
    params:
      docker_enabled: false
    scheduling:
      require:
        - local
  export_remote:
    params:
      docker_enabled: false
    scheduling:
      require:
        - local
  __EXPORT_HISTORY_TO_URI__:
    params:
      docker_enabled: false
    scheduling:
      require:
        - local
  __IMPORT_HISTORY__:
    params:
      docker_enabled: false
    scheduling:
      require:
        - local
  toolshed.g2.bx.psu.edu/repos/goeckslab/tabular_learner/tabular_learner/.*:
    cores: 8
    mem: 32
  toolshed.g2.bx.psu.edu/repos/goeckslab/image_learner/image_learner/.*:
    cores: 8
    mem: 32
  toolshed.g2.bx.psu.edu/repos/goeckslab/ludwig_config_generator/ludwig_config_generator/.*:
    cores: 8
    mem: 64
  toolshed.g2.bx.psu.edu/repos/goeckslab/ludwig_experiment/ludwig_experiment/.*:
    cores: 32
    mem: 240
