tools:
  __DATA_FETCH__:
    params:
      docker_enabled: false
    scheduling:
      require:
        - local
destinations:
  k8s:
    max_accepted_cores: 2
    cores: 2
    max_accepted_mem: 20
    mem: 20
