tools:
  __DATA_FETCH__:
    params:
      docker_enabled: false
    scheduling:
      require:
        - local
  export_remote:
    params:
      docker_enabled: false
    scheduling:
      require:
        - local
  __EXPORT_HISTORY_TO_URI__:
    params:
      docker_enabled: false
    scheduling:
      require:
        - local
  __IMPORT_HISTORY__:
    params:
      docker_enabled: false
    scheduling:
      require:
        - local
