apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-setup-galaxy"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-setup-galaxy"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: "{{ .Values.rbac.serviceAccount }}"
      restartPolicy: Never
      containers:
      - name: kubectl-galaxy-setup
        image: "galaxy/cloudman-server:latest"
        args:
          - "sh"
          - "/scripts/setup_galaxy.sh"
        volumeMounts:
          - name: galaxy-conf-files
            mountPath: /scripts
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - if [ "$(helm status -n {{ .Release.Namespace }} {{ .Release.Name }}-galaxy | grep 'STATUS' | awk -F': ' '{print $2}')" = "deployed" ]; exit 0; else exit 1; fi;
          initialDelaySeconds: {{ .Values.galaxyInstallJob.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.galaxyInstallJob.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.galaxyInstallJob.readinessProbe.failureThreshold }}
          timeoutSeconds: {{ .Values.galaxyInstallJob.readinessProbe.timeoutSeconds }}
      volumes:
        - name: galaxy-conf-files
          configMap:
            name: "{{ .Release.Name }}-galaxykubeman-setup-galaxy"
