apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-pre-delete-job"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      name: "{{ .Release.Name }}-pre-delete-job"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: "{{ .Values.rbac.serviceAccount }}"
      restartPolicy: Never
      containers:
      - name: pre-delete-kubectl
        image: "galaxy/cloudman-server:latest"
        args:
          - "sh"
          - "-c"
          - >
            echo "[`date`] Hibernating the postgres cluster...";
            cluster=$(kubectl get cluster -n {{ .Release.Namespace }} -o jsonpath='{.items[0].metadata.name}');
            kubectl annotate cluster $cluster -n {{ .Release.Namespace }} --overwrite cnpg.io/hibernation=on;
            sleep 20
            echo "[`date`] Deleting the galaxy deployment...";
            helm uninstall -n {{ .Release.Namespace }} {{ .Release.Name }}-galaxy --wait;
            sleep 5;
            kubectl get pv | grep galaxy-pvc | awk '{print $1}' | xargs kubectl delete pv;
            echo "[`date`] Deleting this pre-delete job...";
            kubectl get job -n {{ .Release.Namespace }} -o name | grep -v "pre-delete" | xargs kubectl delete -n {{ .Release.Namespace }};
            echo "[`date`] Pre-delete job has completed.";
