---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-pre-delete-job"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      name: "{{ .Release.Name }}-pre-delete-job"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: "{{ .Values.rbac.serviceAccount }}"
      restartPolicy: Never
      containers:
      - name: pre-delete-kubectl
        image: "galaxy/cloudman-server:latest"
        args:
          - "bash"
          - "/scripts/delete.sh"
        volumeMounts:
          - name: galaxy-conf-files
            mountPath: /scripts
      volumes:
        - name: galaxy-conf-files
          configMap:
            name: "{{ .Release.Name }}-pre-delete-script"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pre-delete-script
  labels:
    app.kubernetes.io/name: {{ include "galaxykubeman.name" . }}
    helm.sh/chart: {{ include "galaxykubeman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  delete.sh: |
    echo "[`date`] Hibernating the postgres cluster..."
    {{- include "galaxykubeman.hibernate-cluster" . | nindent 4 }}
    echo "[`date`] Deleting the galaxy deployment...";
    helm uninstall -n {{ .Release.Namespace }} {{ .Release.Name }}-galaxy --wait;
    sleep 5;
    for pv in $(kubectl get pv -o jsonpath='{.items[?(@.status.phase=="Released")].metadata.name}'); do
      echo "[`date`] Deleting the persistent volume $pv...";
      kubectl patch pv $pv -p '{"metadata":{"finalizers":null}}';
      kubectl delete pv $pv;
    done
    kubectl delete namespace {{ .Release.Namespace }};
    echo "[`date`] Deleting this pre-delete job...";
    kubectl get job -n {{ .Release.Namespace }} -o name | grep -v "pre-delete" | xargs kubectl delete -n {{ .Release.Namespace }};
    echo "[`date`] Pre-delete job has completed.";
