apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-setup-galaxy"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-setup-galaxy"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: "{{ .Values.rbac.serviceAccount }}"
      restartPolicy: Never
      initContainers:
      - name: kubectl-galaxy-setup
        image: "galaxy/cloudman-server:latest"
        args:
          - "sh"
          - "/scripts/setup_galaxy.sh"
        volumeMounts:
          - name: galaxy-conf-files
            mountPath: /scripts
      containers:
      - name: kubectl-galaxy-check
        image: "galaxy/cloudman-server:latest"
        args:
          - "sh"
          - "/scripts/check_galaxy.sh"
        volumeMounts:
          - name: galaxy-conf-files
            mountPath: /scripts
      volumes:
        - name: galaxy-conf-files
          configMap:
            name: "{{ .Release.Name }}-galaxykubeman-setup-galaxy"
