{{- range $key, $entry := .Values.persistence -}}
{{- if $entry -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $entry.name }}-pvc
  labels:
    app.kubernetes.io/name: {{ include "galaxykubeman.name" $ }}
    helm.sh/chart: {{ include "galaxykubeman.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
{{- if $entry.annotations }}
  annotations:
{{ toYaml $entry.annotations | indent 4 }}
{{- end }}
spec:
  {{- if $entry.storageClass }}
  {{- if (eq "-" $entry.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ $entry.storageClass }}"
  {{- end }}
  {{- end }}
  accessModes:
    - {{ $entry.accessMode | quote }}
  resources:
    requests:
      storage: {{ $entry.size | quote }}
  {{- if $entry.extraSpec -}}
  {{- $original := (toYaml $entry.extraSpec) -}}
  {{- $nomultiline := (regexReplaceAll "^^\\s*\\|\\n*" $original "") -}}
  {{- $nowhitespace := (regexReplaceAll "{{\\s*([^}\\s]+)\\s*}}" $nomultiline "{{$1}}") -}}
  {{- tpl $nowhitespace $ | trim | nindent 2 -}}
  {{- end }}

---

{{ if $entry.persistentVolume }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $entry.name }}-pv
  labels:
    name: {{ $entry.name }}-pv
    app.kubernetes.io/name: {{ include "galaxykubeman.name" $ }}
    helm.sh/chart: {{ include "galaxykubeman.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
{{- if $entry.persistentVolume.annotations }}
  annotations:
{{ toYaml $entry.persistentVolume.annotations | indent 4 }}
{{- end }}
spec:
  {{- if $entry.storageClass }}
  {{- if (eq "-" $entry.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ $entry.storageClass }}"
  {{- end }}
  {{- end }}
  accessModes:
    - {{ $entry.accessMode | quote }}
  capacity:
    storage: {{ $entry.size | quote }}
  claimRef:
    namespace: {{ $.Release.Namespace }}
    name: {{ $entry.name }}-pvc
  {{- if $entry.persistentVolume.extraSpec -}}
  {{- $original := (toYaml $entry.persistentVolume.extraSpec) -}}
  {{- $nomultiline := (regexReplaceAll "^^\\s*\\|\\n*" $original "") -}}
  {{- $nowhitespace := (regexReplaceAll "{{\\s*([^}\\s]+)\\s*}}" $nomultiline "{{$1}}") -}}
  {{- tpl $nowhitespace $ | trim | nindent 2 -}}
  {{- end }}

---

{{- end -}}
{{- end -}}
{{- end -}}
