---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "galaxykubeman.pod-priority-class" . }}
value: -1000
preemptionPolicy: Never
globalDefault: false
description: "Galaxy jobs will run when cluster resources are available and will not preempt existing workloads."
