{{- if  .Values.rabbitmq.nodeSelector }}
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: "{{ .Release.Name }}-rabbitmqcluster"
  namespace: {{ .Release.Namespace }}
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - "{{ .Values.rabbitmq.nodeSelector }}"
{{- end }}
