{{- if .Values.secrets }}
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-galaxykubeman-secrets
  labels:
    app.kubernetes.io/name: {{ include "galaxykubeman.name" . }}
    helm.sh/chart: {{ include "galaxykubeman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
kind: Secret
type: Opaque
stringData:
  {{- range $seckey, $secentry := .Values.secrets -}}
  {{- if $secentry -}}
  {{- $seckey | nindent 4 }}: >-
    {{ $secentry | indent 8 -}}
  {{- end -}}
  {{- end }}
---
{{- end -}}